name: Create and attach zip to release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*'
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare files
      run: |
        mkdir -p krystal-vale
        cp -r styles krystal-vale/
        cp .vale.ini krystal-vale/

    - name: Zip files
      run: zip -r krystal-vale.zip krystal-vale/

    - name: Upload zip to release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: krystal-vale.zip
