name: Create and attach zip to release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*'
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare files
      run: |
        mkdir -p vale-package
        cp -r styles vale-package/
        cp .vale.ini vale-package/

    - name: Zip files
      run: zip -r vale-package.zip vale-package/

    - name: Upload zip to release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: vale-package.zip
